name: Build
on:
  push:
    branches:
      - main

jobs:
  build-go:
    name: Build Wireguard Go
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: WireGuard/wireguard-go
          path: wireguard-go
      - uses: actions/setup-go@v5
      - run: make -C wireguard-go
        env:
          GOARCH: arm
          GOOS: linux

      - uses: actions/upload-artifact@v4
        with:
          name: wireguard-go
          path: wireguard-go/wireguard-go

  build-tools:
    name: Build Wireguard tools
    runs-on: ubuntu-latest
    steps:
      - uses: docker/setup-qemu-action@v3
        with:
          platforms: arm

      - uses: actions/checkout@v4
        with:
          repository: WireGuard/wireguard-tools
          path: wireguard-tools
      - run: |
          docker run --platform linux/arm/v7 --rm -v $(pwd)/wireguard-tools:/work -w /work tjjh89017/wg-m5 bash -c 'PLATFORM=unix CFLAGS="-O3 -U__linux__" LDFLAGS=-static make -C src'

      - uses: actions/upload-artifact@v4
        with:
          name: wg
          path: wireguard-tools/src/wg

      - uses: actions/upload-artifact@v4
        with:
          name: wg-quick
          path: wireguard-tools/src/wg-quick/linux.bash
