name: Build
on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build Wireguard
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: docker/setup-qemu-action@v3
        with:
          platforms: arm

      - uses: docker/setup-buildx-action@v3
      - run: |
          docker buildx build --platform linux/arm/v7 -t arm-build .

      - uses: actions/checkout@v4
        with:
          repository: WireGuard/wireguard-go
          path: wireguard-go
      - run: |
          docker run --rm -v $(pwd)/wireguard-go:/work -w /work arm-build make

      - uses: actions/checkout@v4
        with:
          repository: WireGuard/wireguard-tools
          path: wireguard-tools
      - run: |
          docker run --rm -v $(pwd)/wireguard-tools:/work -w /work arm-build make PLATFORM=unix

      - uses: actions/upload-artifact@v4
        with:
          name: wireguard-go
          path: wireguard-go/wireguard-go

      - uses: actions/upload-artifact@v4
        with:
          name: wg
          path: wireguard-tools/src/wg

      - uses: actions/upload-artifact@v4
        with:
          name: wg-quick
          path: wireguard-tools/src/wg-quick/linux.bash
